apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: lex-application
  name: lex-application
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lex-application
  strategy:
    rollingUpdate:
     maxSurge: 25%
     maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lex-application
    spec:
      containers:
      - image: saurabhkumardocker/lex-office:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: lex-application
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lex-application
  name: lex-application
  namespace: default
spec:
  ports:
  - nodePort: 31728
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: lex-application
  type: LoadBalancer